# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Deploy emailservice v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-v1
  labels:
    app: emailservice
    version: v1
spec:
  selector:
    matchLabels:
      app: emailservice
      version: v1
  template:
    metadata:
      labels:
        app: emailservice
        version: v1
    spec:
      serviceAccountName: emailservice
      containers:
      - name: server
        image: emailservice:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
# Deploy emailservice v2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-v2
  labels:
    app: emailservice
    version: v2
spec:
  selector:
    matchLabels:
      app: emailservice
      version: v2
  template:
    metadata:
      labels:
        app: emailservice
        version: v2
    spec:
      serviceAccountName: emailservice
      containers:
      - name: server
        image: emailservice:v2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice

---